from cothread.catools import caget, caput, DBR_STRING
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
import numpy as np
from reportlab.lib.pagesizes import letter, inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image, PageBreak, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from cothread import Sleep
import os

props = dict(boxstyle='round', facecolor='wheat', alpha=0.9)
good = dict(boxstyle='round', facecolor='palegreen', alpha=0.9)
bad = dict(boxstyle='round', facecolor='pink', alpha=0.9)

#os.environ['EPICS_CA_DEBUG'] = '0'
#os.environ['EPICS_CA_AUTO_ADDR_LIST'] = 'NO'
#os.environ['EPICS_CA_ADDR_LIST'] = '127.0.0.1'

PSCsn = input('\nEnter PSC serial number: (Enter "H" for help, Default="009"):')
if(PSCsn=="H"):
    print('Stopping Program.  Serial Number is on the ITR document attached to the PSC Chassis')
    exit()
elif(PSCsn==""):
    PSCsn="009"
PVprefix = input('\nEnter the PV prefix for this device (Default="lab{2}):')
if(PVprefix==""):
    PVprefix = "lab{2}"
print("PVprefix = ",PVprefix)

freport = 'PSC'+PSCsn+'.pdf'   #File Generated by this script for the  Report
if os.path.exists(freport):
    x = input("\n\nFile Exists! Make sure this file is not in use then\nEnter '1' to overwrite or '0' to abort: ")
    if int(x)==1:
        try:
            os.rename(freport,freport)
            print("Available!")
        except OSError as e:
            print("****** ERROR ******\n\n"+freport+" is in use. Please close the file and try again.")
            exit()
    else:
        exit()

# Create the Report Document....
doc = SimpleDocTemplate(freport, pagesize=letter, rightMargin=30,leftMargin=30, topMargin=30,bottomMargin=18)
styles = getSampleStyleSheet()
elements = []
    
#EPICS PVs for PSC IOC:
# PSC Device Type PVs:
NumChan = PVprefix+"NumChannels-Mode"
Resolution = PVprefix+"Resolution-Mode"
Bandwidth = PVprefix+"Bandwidth-Mode"
Polarity = PVprefix+"Polarity-Mode"

NC = caget(NumChan,datatype=DBR_STRING)
Res = caget(Resolution,datatype=DBR_STRING)
BW = caget(Bandwidth,datatype=DBR_STRING)
Pol = caget(Polarity,datatype=DBR_STRING)
CHmax = 2
if(NC=="4 Channel"): CHmax = 4
print("This PSC has ",CHmax," Channels")

tdata = []
tdata.append(["PSC Functional Test Results",0])
tdata.append(["Power Supply Controller Configuration",0])
tdata.append(["Serial Number", PSCsn])
tdata.append(["Number of Channels",NC])
tdata.append(["Resolution",Res])
tdata.append(["Bandwidth",BW])
tdata.append(["Polarity",Pol])

rowH = [0.4*inch,0.35*inch,0.27*inch,0.27*inch,0.27*inch,0.27*inch,0.27*inch]
colH = [3*inch,3*inch]

ta=Table(tdata,colH,rowH,style=[
                ('SPAN',(0,0),(1,0)),
                ('SPAN',(0,1),(1,1)),
                ('ALIGN',(0,0),(1,1),'CENTER'),
                ('FONTSIZE', (0,0), (1,0), 16),
                ('FONTSIZE', (0,1), (1,1), 14),
                ('VALIGN',(0,0),(1,6),'MIDDLE'),
                ('LINEABOVE',(0,1),(1,2),2,colors.black),
                ('BACKGROUND',(0,0),(1,1),colors.lemonchiffon),
                ('BACKGROUND',(0,2),(0,6),colors.lightblue),
                
                ('FONTSIZE', (0,1), (1,6), 12),
                ('GRID',(0,0),(-1,-1),1,colors.black),
                ('BOX',(0,0),(-1,-1),2,colors.black),
                ])

elements.append(ta)

print(NC,Res,BW,Pol)

#EVR Timing Test.........................................
# EVR Timing PVs:
EvrTS = PVprefix+"TS-S-I"
EVRdate = PVprefix+"Timestamp-I.VALA"
TS = []
Telapse=[]
T0 = caget(EvrTS)
Date = caget(EVRdate)
Tlast = T0
i = 0;
TSerror = 0
zeroCnt = 0
print("Collecting 30 seconds of EVR Timestamps:")
f,ax = plt.subplots(1,1,figsize=(7,5))
plt.ion()
while(i<31):
	TM = caget(EvrTS)
	TD = TM - Tlast
	print(TM,TD)
	if(TD>0):
	    Telapse.append(TM-T0)
	    if(TD!=1): TSerror = 1
	    TS.append(TM-T0)
	    print("TD=%d EvrTS[%d] = %d  : Error = %d" % (TD,i,TM,TSerror))
	    Tlast = TM
	    i = i + 1
	    zeroCnt = 0
	else:
	    zeroCnt = zeroCnt + 1
	    if(zeroCnt>5):
	        print("Timestamp Not Changed for 5 seconds. Stopping Program.")
	        exit()
	Sleep(0.7)
	ax.clear()
	ax.plot(Telapse,TS,"-o")
	ax.grid(True)
	ax.set_xlabel("Elapsed Time (Seconds)")
	ax.set_ylabel("TmStamp - T0")
	ax.set_title("EVR Timestamp Test")
	mstr ="T0: "+str(T0)+" = "+bytes(Date).decode('utf-8').rstrip('\x00')
	ax.text(0.05, 0.95,mstr,transform=ax.transAxes, fontsize=10,verticalalignment='top', bbox=props)
	plt.pause(0.01)
# if TSerror != 0 then this test has failed.
if(TSerror==0):
	mstr = "Test: All time increments equal 1 second? : PASS"
	ax.text(0.2, 0.1,mstr,transform=ax.transAxes, fontsize=12,verticalalignment='top', bbox=good)
	print("EVR Timestamp Test PASSED.")
else:
	mstr = "Test: All time increments equal 1 second? : FAIL"
	ax.text(0.2, 0.1,mstr,transform=ax.transAxes, fontsize=12,verticalalignment='top', bbox=bad)
	print("EVR Timestamp Test FAILED.")
plt.pause(0.01)
f.savefig('EVR_TimeStamp.png')
# Add Timestamp Test to the Report....
Sleep(1)
plt.ioff()
plt.close(f)
f.canvas.flush_events()   # ensure all GUI events are handled
plt.pause(0.1)

im = Image('EVR_TimeStamp.png',6*inch,4*inch)
elements.append(im)
######################################################################
# Start of the Big Loop!
######################################################################
AteIgndChan = "PSCtest:Ignd:Channel-SP"
caput("PSCtest:CH1:Vmon:Gain-SP",0.5)
caput("PSCtest:CH1:Imon:Gain-SP",0.25)
caput("PSCtest:CH2:Vmon:Gain-SP",0.5)
caput("PSCtest:CH2:Imon:Gain-SP",0.25)
caput("PSCtest:CH3:Vmon:Gain-SP",0.5)
caput("PSCtest:CH3:Imon:Gain-SP",0.25)
caput("PSCtest:CH4:Vmon:Gain-SP",0.5)
caput("PSCtest:CH4:Imon:Gain-SP",0.25)
caput(AteIgndChan,3)
Sleep(1)
for chan in range(1,(CHmax+1)):
	CHprefix = "Chan"+str(chan)+":"
	print("Top of Loop",chan,CHprefix)
	PWR = PVprefix+CHprefix+"DigOut_ON1-SP"
	ENB = PVprefix+CHprefix+"DigOut_ON2-SP"
	PRK = PVprefix+CHprefix+"DigOut_Park-SP"
	DacSP = PVprefix+CHprefix+"DAC_SetPt-SP"
	RATE = PVprefix+CHprefix+"SF:AmpsperSec-SP"
	caput(DacSP,0)
	caput(PWR,0)
	caput(ENB,0)
	caput(PRK,0)
	caput(RATE,4)
	###################################################################    
	# ATE Fault Tests:
	###################################################################
	LiveFault = PVprefix+CHprefix+"FaultsLive-I"
	LatFault = PVprefix+CHprefix+"FaultsLat-I"
	ClrFault = PVprefix+CHprefix+"FaultClear-SP"
	Fault1 = PVprefix+CHprefix+"FaultMask:B7-SP"
	Fault2 = PVprefix+CHprefix+"FaultMask:B8-SP"
	Fault3 = PVprefix+CHprefix+"FaultMask:B9-SP"
	RST = PVprefix+CHprefix+"DigOut_Reset-SP"

	#ATE PVs Used here:
	AteChanFault = "PSCtest:CH"+str(chan)+":Fault-SP"
	AteDcctFault = "PSCtest:DCCT:Fault:Channel-SP"
	AteIgndChan = "PSCtest:Ignd:Channel-SP"
	AteIgndVal = "PSCtest:Ignd-SP"

	caput(AteDcctFault,0)   #Set ATE DCCT Fault to "NONE"
	caput(AteIgndChan,(chan-1)) #Select Channel for Ignd Setting
	Sleep(1)
	IgndSP = 0.1
	caput(AteIgndVal,IgndSP)   #Set Ignd to something sensible, like 0.1A
	IgndSP = 0.1
	Sleep(5)

	tdata = []
	tdata.append(["ATE Fault Tests for Channel "+str(chan),0])

	caput(AteChanFault,2)
	caput(DacSP,0)
	caput(PWR,0)
	caput(ENB,0)
	caput(PRK,0)
	caput(RST,1)
	Sleep(1)
	caput(ClrFault,1)
	Sleep(1)
	caput(RST,0)
	caput(Fault1,1)
	caput(Fault2,1)
	caput(Fault3,1)
	tcolor=[]
	print("RESET",caget(LiveFault),caget(LatFault))
	if(caget(LiveFault)==0 and caget(LatFault)==0):
		tdata.append(["All Faults Successfully Cleared","PASS"])
		tcolor.append(0)
	else:
		tdata.append(["All Faults Successfully Cleared","FAIL"])
		tcolor.append(1)
	#Set Fault 1:
	caput(AteChanFault,0)
	Count = 0
	error = 0
	while((caget(LiveFault)&0x80==0 or caget(LatFault)&0x80==0) and error==0):
		Sleep(1)
		print(caget(LiveFault),caget(LatFault))
		Count = Count + 1
		if(Count>10): error = 1
	if(error==0):
		tdata.append(["Fault #1 Generated and Detected","PASS"])
		tcolor.append(0)
	else:
		tdata.append(["Fault #1 Generated and Detected","FAIL"])
		tcolor.append(1)
	#Set Fault 2:
	caput(RST,1)
	Sleep(1)
	caput(ClrFault,1)
	Sleep(1)
	caput(RST,0)
	Sleep(1)
	Count=0
	while((caget(LiveFault)!=0 or caget(LatFault)!=0) and Count!=10 ):
		Sleep(1)
		Count = Count + 1
		print("Waiting...",Count)
	print("RESET:",caget(LiveFault),caget(LatFault))
	if(caget(LiveFault)==0 and caget(LatFault)==0):
		tdata.append(["Fault #1 Successfully Cleared","PASS"])
		tcolor.append(0)
	else:
		tdata.append(["Fault #1 Successfully Cleared","FAIL"])
		tcolor.append(1)
	caput(AteChanFault,1)
	Count = 0
	error = 0
	while((caget(LiveFault)&0x100==0 or caget(LatFault)&0x100==0) and error==0):
		Sleep(1)
		print(caget(LiveFault),caget(LatFault))
		Count = Count + 1
		if(Count>10): error = 1
	if(error==0):
		tdata.append(["Fault #2 Generated and Detected","PASS"])
		tcolor.append(0)
	else:
		tdata.append(["Fault #2 Generated and Detected","FAIL"])
		tcolor.append(1)
	#Set Fault 3:
	caput(RST,1)
	Sleep(1)
	caput(ClrFault,1)
	Sleep(1)
	caput(RST,0)
	Sleep(1)
	Count=0
	while((caget(LiveFault)!=0 or caget(LatFault)!=0) and Count!=10 ):
		Sleep(1)
		Count = Count + 1
		print("Waiting for Faults to Clear...",Count)
	print("RESET:",caget(LiveFault),caget(LatFault))
	if(caget(LiveFault)==0 and caget(LatFault)==0):
		tdata.append(["Fault #2 Successfully Cleared","PASS"])
		tcolor.append(0)
	else:
		tdata.append(["Fault #2 Successfully Cleared","FAIL"])
		tcolor.append(1)
	caput(AteChanFault,2)
	Count = 0
	error = 0
	while((caget(LiveFault)&0x200==0 or caget(LatFault)&0x200==0) and error==0):
		Sleep(1)
		print(caget(LiveFault),caget(LatFault))
		Count = Count + 1
		if(Count>10): error = 1
	if(error==0):
		tdata.append(["Fault #3 Generated and Detected","PASS"])
		tcolor.append(0)
	else:
		tdata.append(["Fault #3 Generated and Detected","FAIL"])
		tcolor.append(1)
	caput(RST,1)
	Sleep(1)
	caput(ClrFault,1)
	Sleep(1)
	caput(RST,0)
	Sleep(1)
	Count=0
	while((caget(LiveFault)!=0 or caget(LatFault)!=0) and Count!=10 ):
		Sleep(1)
		Count = Count + 1
		print("Waiting for Faults to Clear...",Count)
	print("RESET:",caget(LiveFault),caget(LatFault))
	if(caget(LiveFault)==0 and caget(LatFault)==0):
		tdata.append(["Fault #3 Successfully Cleared","PASS"])
		tcolor.append(0)
	else:
		tdata.append(["Fault #3 Successfully Cleared","FAIL"])
		tcolor.append(1)
		
	caput(AteDcctFault,chan)
	Sleep(1)
	Count = 0
	error = 0
	while((caget(LiveFault)&0x40==0 or caget(LatFault)&0x40==0) and error==0):
		Sleep(1)
		print(caget(LiveFault),caget(LatFault))
		Count = Count + 1
		if(Count>10): error = 1
	print(caget(LiveFault),caget(LatFault))
	if(error==0):
		tdata.append(["DCCT Fault Generated and Detected","PASS"])
		tcolor.append(0)
	else:
		tdata.append(["DCCT Fault Generated and Detected","FAIL"])
		tcolor.append(1)
	caput(RST,1)
	caput(AteDcctFault,0) #Reset the ATE DCCT Fault to "NONE"
	Sleep(5)
	caput(ClrFault,1)
	Sleep(1)
	caput(RST,0)
	Sleep(1)
	Count=0
	while((caget(LiveFault)!=0 or caget(LatFault)!=0) and Count!=10 ):
		Sleep(1)
		Count = Count + 1
		print("Waiting for Faults to Clear...",Count)
	print("RESET:",caget(LiveFault),caget(LatFault))
	if(caget(LiveFault)==0 and caget(LatFault)==0):
		tdata.append(["DCCT Fault Successfully Cleared","PASS"])
		tcolor.append(0)
	else:
		tdata.append(["DCCT Fault Successfully Cleared","FAIL"])
		tcolor.append(1)

	rowH = [0.35*inch,0.27*inch,0.27*inch,0.27*inch,0.27*inch,0.27*inch,0.27*inch,0.27*inch,0.27*inch,0.27*inch]
	colH = [4*inch,2*inch]

	style=[('SPAN',(0,0),(1,0)),
		   ('ALIGN',(0,0),(1,0),'CENTER'),
		   ('FONTSIZE', (0,0), (1,0), 16),
		   ('FONTSIZE', (0,1), (1,1), 14),
		   ('VALIGN',(0,0),(1,6),'MIDDLE'),
		   ('LINEABOVE',(0,1),(1,1),2,colors.black),
		   ('LINEAFTER',(0,1),(0,9),2,colors.black),
		   ('BACKGROUND',(0,0),(1,0),colors.lemonchiffon),
		   ('BACKGROUND',(0,1),(0,9),colors.lightblue),              
		   ('FONTSIZE', (0,1), (1,9), 12),
		   ('GRID',(0,0),(-1,-1),1,colors.black),
		   ('BOX',(0,0),(-1,-1),2,colors.black)]

	for i in range(0,9):
		if(tcolor[i]==0):
		    style.append(('BACKGROUND',(1,i+1),(1,i+1),colors.lightgreen))
		else:
		    style.append(('BACKGROUND',(1,i+1),(1,i+1),colors.pink))
		    
	ta=Table(tdata,colH,rowH,style=style)
	elements.append(Spacer(width=1,height=0.2*inch))
	elements.append(ta)
	#############################################################################
	# Power Supply Regulation Test
	#############################################################################
	# Additional PSC PVs:
	DacSP = PVprefix+CHprefix+"DAC_SetPt-SP"
	PSMode = PVprefix+CHprefix+"DAC_OpMode-SP"
	EXT = PVprefix+CHprefix+"DigOut_Spare-SP"
	ON = PVprefix+CHprefix+"DigIn-I.B0"
	DCCT1 = PVprefix+CHprefix+"DCCT1-I"
	DCCT2 = PVprefix+CHprefix+"DCCT2-I"
	DAC = PVprefix+CHprefix+"DAC-I"
	RATE = PVprefix+CHprefix+"SF:AmpsperSec-SP"
	caput(RATE,10)
	caput(DacSP,0)
	caput(ENB,1)
	caput(PRK,1)
	caput(PWR,1)
	Sleep(1)
	ONstat = caget(ON)
	Sleep(5)
	caput(PSMode,0)
	caput(PRK,0)
	if(CHmax==2):
	    if(chan==1):
	        SP = 30
	    else:
	        SP = 50
	else:
	    SP = 10
	caput(DacSP,SP)
	Sleep(10)
	# Collect 1 minute of data:
	LRB = []
	D1RB = []
	D2RB = []
	f,ax = plt.subplots(3,1,figsize=(6,9.5))
	plt.ion()
	for i in range(0,180):
		X = caget([DAC,DCCT1,DCCT2])
		LRB.append(X[0])
		D1RB.append(X[1])
		D2RB.append(X[2])
		ax[0].clear()
		ax[1].clear()
		ax[2].clear()
		ax[0].plot(LRB)
		ax[1].plot(D1RB)
		ax[2].plot(D2RB)
		plt.pause(0.1)
		Sleep(0.3)

	plt.ioff()
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	LRBavg = np.mean(LRB)
	LRB = np.subtract(LRB,LRBavg)
	LRB = np.multiply(LRB,1000)
	LRBerr = abs(LRBavg-SP)
	D1RBavg = np.mean(D1RB)
	D1RB = np.subtract(D1RB,D1RBavg)
	D1RB = np.multiply(D1RB,1000)
	D1RBerr = abs(D1RBavg+SP)
	D2RBavg = np.mean(D2RB)
	D2RB = np.subtract(D2RB,D2RBavg)
	D2RB = np.multiply(D2RB,1000)
	D2RBerr = abs(D2RBavg+SP)
	print(LRBerr,D1RBerr,D2RBerr)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(LRB)
	ax1.grid(True)
	ax1.set_xlabel("Samples")
	ax1.set_ylabel("(Reading - Average) (mA)")
	ax1.set_title("Loopback Stability (SP="+str(SP)+"A)")
	mstr ="Loopback Avg: "+str(round(LRBavg,5))+"A"
	ax1.text(0.02, 0.97,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=props)
	if(LRBerr<0.050):
		mstr ="Test: |Avg-SP|<50mA?  PASS"
		ax1.text(0.5, 0.07,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=good)
	else:
		mstr ="Test: |Avg-SP|<50mA?  FAIL"
		ax1.text(0.5, 0.07,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=bad)
		
	ax2.hist(LRB,bins=20,color='blue',edgecolor='black')
	ax2.grid(True)
	ax2.set_axisbelow(True)
	ax2.set_xlabel("Deviation from Average (mA)")
	ax2.set_ylabel("Frequency")
	ax2.set_title("Loopback Deviation")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_Loopback_Stability.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(D1RB)
	ax1.grid(True)
	ax1.set_xlabel("Samples")
	ax1.set_ylabel("(Reading - Average) (mA)")
	ax1.set_title("DCCT1 Stability (SP="+str(SP)+"A)")
	mstr ="DCCT1 Avg: "+str(round(D1RBavg,5))+"A"
	ax1.text(0.02, 0.97,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=props)
	print("D1RBerr = ",D1RBerr,D1RBavg,SP)
	if(D1RBerr<0.050):
		mstr ="Test: |Avg-SP|<50mA?  PASS"
		ax1.text(0.5, 0.07,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=good)
	else:
		mstr ="Test: |Avg-SP|<50mA?  FAIL"
		ax1.text(0.5, 0.07,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=bad)

	ax2.hist(D1RB,bins=20,color='blue',edgecolor='black')
	ax2.grid(True)
	ax2.set_axisbelow(True)
	ax2.set_xlabel("Deviation from Average (mA)")
	ax2.set_ylabel("Frequency")
	ax2.set_title("DCC1 Deviation")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_DCCT1_Stability.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(D2RB)
	ax1.grid(True)
	ax2.set_axisbelow(True)
	ax1.set_xlabel("Samples")
	ax1.set_ylabel("(Reading - Average) (mA)")
	ax1.set_title("DCCT2 Stability (SP="+str(SP)+"A)")
	mstr ="DCCT2 Avg: "+str(round(D2RBavg,5))+"A"
	ax1.text(0.02, 0.97,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=props)
	if(D2RBerr<0.050):
		mstr ="Test: |Avg-SP|<50mA?  PASS"
		ax1.text(0.5, 0.07,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=good)
	else:
		mstr ="Test: |Avg-SP|<50mA?  FAIL"
		ax1.text(0.5, 0.07,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=bad)
		
	ax2.hist(D2RB,bins=20,color='blue',edgecolor='black')
	ax2.grid(True)
	ax2.set_xlabel("Deviation from Average (mA)")
	ax2.set_ylabel("Frequency")
	ax2.set_title("DCC2 Deviation")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_DCCT2_Stability.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	mstr = "Power Supply Regulation for Channel "+str(chan)+":"
	Pstyle = ParagraphStyle(
		'Custom',
		parent=styles['Normal'],
		fontName='Helvetica',
		fontSize=16,        # 👈 Set font size here
		leading=20,          # Optional: line spacing
		alignment=TA_CENTER   # 👈 Centers the paragraph horizontally
	)

	title = Paragraph(mstr,Pstyle)
	elements.append(PageBreak())  
	elements.append(title)
	im = Image('Chan'+str(chan)+'_Loopback_Stability.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_DCCT1_Stability.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_DCCT2_Stability.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))

####################################################################
# Jump Test
####################################################################
	# Jump test PVs:
	Shot = PVprefix+CHprefix+"SS:Trig:Usr"
	DACwfm = PVprefix+CHprefix+"USR:DAC-Wfm"
	D1wfm = PVprefix+CHprefix+"USR:DCCT1-Wfm"
	D2wfm = PVprefix+CHprefix+"USR:DCCT2-Wfm"
	ERRwfm = PVprefix+CHprefix+"USR:Error-Wfm"
	REGwfm = PVprefix+CHprefix+"USR:Reg-Wfm"
	VOLTwfm = PVprefix+CHprefix+"USR:Volt-Wfm"
	GNDwfm = PVprefix+CHprefix+"USR:Gnd-Wfm"
	SPRwfm = PVprefix+CHprefix+"USR:Spare-Wfm"
	XMAX = PVprefix+CHprefix+"SS:WFM-Xmax"
	XMIN = PVprefix+CHprefix+"SS:WFM-Xmin"
	ACTV = PVprefix+CHprefix+"UsrTrigActive-I"

	caput(XMIN,0)       #Set Snapshot Min to 0
	caput(XMAX,100000)  #Set Snapshot Max to 100000 10KHz Samples
	caput(PSMode,3)     #Set Mode to Jump
	if(CHmax==2):
	    if(chan==1):
	        SP = 30.05
	    else:
	        SP = 50.05
	else:
	    SP = 10.05
	caput(DacSP,SP)  #Set DAC SP to 0.05 Amps Higher from the previous setting
	Sleep(.1)
	caput(Shot,1)       #Take the Snapshot.
	Sleep(2)
	while(caget(ACTV)>0):
		Sleep(1)
		print("Wating for Jump Snapshot data.....")
	DAC = caget(DACwfm)
	D1 = caget(D1wfm)
	D2 = caget(D2wfm)
	ERR = caget(ERRwfm)
	REG = caget(REGwfm)
	VOLT = caget(VOLTwfm)
	GND = caget(GNDwfm)
	SPR = caget(SPRwfm)

	Tindex = np.argmax(ERR)
	DACTRAN = []
	ERRTRAN = []
	D1TRAN = []
	D2TRAN = []
	REGTRAN = []
	VTRAN = []
	GTRAN = []
	STRAN = []

	if(Tindex>500 and Tindex<98000):
		for i in range((Tindex-500),(Tindex+500)):
		    DACTRAN.append(DAC[i])
		    ERRTRAN.append(ERR[i])
		    D1TRAN.append(D1[i])
		    D2TRAN.append(D2[i])
		    REGTRAN.append(REG[i])
		    VTRAN.append(VOLT[i])
		    GTRAN.append(GND[i])
		    STRAN.append(SPR[i])
		            
	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(DAC)
	ax1.grid(True)
	ax1.set_xlabel("10KHz Samples")
	ax1.set_ylabel("Current (A)")
	ax1.set_title("DAC Loopback Jump Test")
		
	ax2.plot(DACTRAN)
	ax2.grid(True)
	ax2.set_xlabel("10KHz Samples")
	ax2.set_ylabel("Current (A)")
	ax2.set_title("DAC Transition")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_DAC_Jump.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(ERR)
	ax1.grid(True)
	ax1.set_xlabel("10KHz Samples")
	ax1.set_ylabel("Current (A)")
	ax1.set_title("ERROR Jump Test")
    
	ax2.plot(ERRTRAN)
	ax2.grid(True)
	ax2.set_xlabel("10KHz Samples")
	ax2.set_ylabel("Current (A)")
	ax2.set_title("Error Transition")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_ERROR_Jump.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(D1)
	ax1.grid(True)
	ax1.set_xlabel("10KHz Samples")
	ax1.set_ylabel("Current (A)")
	ax1.set_title("DCCT1 Jump")
		
	ax2.plot(D1TRAN)
	ax2.grid(True)
	ax2.set_xlabel("10KHz Samples")
	ax2.set_ylabel("Current (A)")
	ax2.set_title("DCCT1 Transition")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_DCCT1_Jump.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(D2)
	ax1.grid(True)
	ax1.set_xlabel("10KHz Samples")
	ax1.set_ylabel("Current (A)")
	ax1.set_title("DCCT2 Jump Test")
    
	ax2.plot(D2TRAN)
	ax2.grid(True)
	ax2.set_xlabel("10KHz Samples")
	ax2.set_ylabel("Current (A)")
	ax2.set_title("DCCT2 Transition")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_DCCT2_Jump.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(REG)
	ax1.grid(True)
	ax1.set_xlabel("10KHz Samples")
	ax1.set_ylabel("Current (A)")
	ax1.set_title("Regulator Jump Test")
		
	ax2.plot(REGTRAN)
	ax2.grid(True)
	ax2.set_xlabel("10KHz Samples")
	ax2.set_ylabel("Current (A)")
	ax2.set_title("REG Transition")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_REG_Jump.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(VOLT)
	ax1.grid(True)
	ax1.set_xlabel("10KHz Samples")
	ax1.set_ylabel("Voltage (V)")
	ax1.set_title("PS VOLT Jump Test")
    
	ax2.plot(VTRAN)
	ax2.grid(True)
	ax2.set_xlabel("10KHz Samples")
	ax2.set_ylabel("Voltage (V)")
	ax2.set_title("VOLT Transition")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_VOLT_Jump.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	IgndAvg = float(np.mean(GND))
	print("####################IgndAvg=",IgndAvg,IgndSP)
	Diff = abs(IgndSP - IgndAvg)
	ax1.plot(GND)
	ax1.grid(True)
	ax1.set_xlabel("10KHz Samples")
	ax1.set_ylabel("Current (A)")
	ax1.set_title("IGND Jump Test")
	mstr ="Ignd SP: "+str(round(IgndSP,3))+"A"
	ax1.text(0.02, 0.97,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=props)
	mstr ="Ignd Wfm Avg: "+str(round(IgndAvg,3))+"A"
	ax1.text(0.6, 0.97,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=props)
	if(Diff>0.05):
	    mstr ="Test: |IgndSP-IgndAvg|<50mA? : FAIL"	
	    ax1.text(0.3, 0.07,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=bad)
	else:
	    mstr ="Test: |IgndSP-IgndAvg|<50mA? : PASS"
	    ax1.text(0.3, 0.07,mstr,transform=ax1.transAxes, fontsize=10,verticalalignment='top', bbox=good)
	    	
	ax2.plot(GTRAN)
	ax2.grid(True)
	ax2.set_xlabel("10KHz Samples")
	ax2.set_ylabel("Current (A)")
	ax2.set_title("IGND Transition")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_IGND_Jump.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f = plt.figure(figsize=(8,4))
	gs = GridSpec(1,3,figure=f)
	ax1 = f.add_subplot(gs[0, 0:2])
	ax2 = f.add_subplot(gs[0, 2])

	ax1.plot(SPR)
	ax1.grid(True)
	ax1.set_xlabel("10KHz Samples")
	ax1.set_ylabel("Current (A)")
	ax1.set_title("SPARE Jump Test")
    
	ax2.plot(STRAN)
	ax2.grid(True)
	ax2.set_xlabel("10KHz Samples")
	ax2.set_ylabel("Current (A)")
	ax2.set_title("SPARE Transition")
	plt.tight_layout()
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_SPARE_Jump.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	mstr = "Jump Test Results:"
	Pstyle = ParagraphStyle(
		'Custom',
		parent=styles['Normal'],
		fontName='Helvetica',
		fontSize=16,        # 👈 Set font size here
		leading=20,          # Optional: line spacing
		alignment=TA_CENTER   # 👈 Centers the paragraph horizontally
	)

	title = Paragraph(mstr,Pstyle)
	elements.append(PageBreak())  
	elements.append(title)
	im = Image('Chan'+str(chan)+'_DAC_Jump.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_DCCT1_Jump.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_DCCT1_Jump.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))

	elements.append(PageBreak())  
	elements.append(title)
	im = Image('Chan'+str(chan)+'_ERROR_Jump.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_REG_Jump.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_VOLT_Jump.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))

	elements.append(PageBreak())  
	elements.append(title)
	im = Image('Chan'+str(chan)+'_IGND_Jump.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_SPARE_Jump.png',7*inch,3*inch)
	elements.append(im)

####################################################################
# Smooth Ramp Test
####################################################################
	# PVs for Smooth Test:
	RATE = PVprefix+CHprefix+"SF:AmpsperSec-SP"

	caput(PSMode,0)    #Set PS Mode to SMOOTH
	caput(RATE,10)     #Set Ramp Rate to 10 Amps/Sec
	if(CHmax==2):
	    if(chan==1):
	        caput(DacSP,0) #Set DAC to 0 Amps
	        Sleep(10) 
	        caput(DacSP,49.9)  #Set DAC SP to +49.9 Amps
	    else:
	        caput(RATE,20)     #Set Ramp Rate to 20 Amps/Sec
	        caput(DacSP,0) #Set DAC to 0 Amps
	        Sleep(10) 
	        caput(DacSP,99.9)  #Set DAC SP to +99.9 Amps
	else:
	    caput(DacSP,-23.9) #Set DAC to -23.9 Amps
	    Sleep(10)           #Wait 10 Seconds for Ramp to Complete
	    caput(DacSP,23.9)  #Set DAC SP to +23.9 Amps
	Sleep(2)           #Wait 2 Seconds before taking Snapshot
	caput(Shot,1)      #Take the Snapshot.
	Sleep(2)
	while(caget(ACTV)>0):
		Sleep(1)
		print("Wating for Smooth Snapshot data.....")
		
	DAC = caget(DACwfm)
	D1 = caget(D1wfm)
	D2 = caget(D2wfm)
	ERR = caget(ERRwfm)
	REG = caget(REGwfm)
	VOLT = caget(VOLTwfm)
	GND = caget(GNDwfm)
	SPR = caget(SPRwfm)

	f,ax = plt.subplots(figsize=(8,4))
	ax.plot(DAC)
	ax.grid(True)
	ax.set_xlabel("10KHz Samples")
	ax.set_ylabel("Current (A)")
	ax.set_title("DAC Loopback Smooth Test")
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_DAC_Smooth.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f,ax = plt.subplots(figsize=(8,4))
	ax.plot(D1)
	ax.grid(True)
	ax.set_xlabel("10KHz Samples")
	ax.set_ylabel("Current (A)")
	ax.set_title("DCCT1 Smooth Test")
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_DCCT1_Smooth.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f,ax = plt.subplots(figsize=(8,4))
	ax.plot(D2)
	ax.grid(True)
	ax.set_xlabel("10KHz Samples")
	ax.set_ylabel("Current (A)")
	ax.set_title("DCCT2 Smooth Test")
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_DCCT2_Smooth.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f,ax = plt.subplots(figsize=(8,4))
	ax.plot(ERR)
	ax.grid(True)
	ax.set_xlabel("10KHz Samples")
	ax.set_ylabel("Current (A)")
	ax.set_title("ERROR Smooth Test")
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_ERROR_Smooth.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f,ax = plt.subplots(figsize=(8,4))
	ax.plot(REG)
	ax.grid(True)
	ax.set_xlabel("10KHz Samples")
	ax.set_ylabel("Current (A)")
	ax.set_title("REG Smooth Test")
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_REG_Smooth.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f,ax = plt.subplots(figsize=(8,4))
	ax.plot(VOLT)
	ax.grid(True)
	ax.set_xlabel("10KHz Samples")
	ax.set_ylabel("Voltage (V)")
	ax.set_title("PS VOLT Smooth Test")
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_VOLT_Smooth.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f,ax = plt.subplots(figsize=(8,4))
	IgndAvg = float(np.mean(GND))
	Diff = abs(IgndSP - IgndAvg)
	ax.plot(GND)
	ax.grid(True)
	ax.set_xlabel("10KHz Samples")
	ax.set_ylabel("Current (A)")
	ax.set_title("IGND Smooth Test")
	mstr ="Ignd SP: "+str(round(IgndSP,3))+"A"
	ax.text(0.02, 0.97,mstr,transform=ax.transAxes, fontsize=10,verticalalignment='top', bbox=props)
	mstr ="Ignd Wfm Avg: "+str(round(IgndAvg,3))+"A"
	ax.text(0.6, 0.97,mstr,transform=ax.transAxes, fontsize=10,verticalalignment='top', bbox=props)
	if(Diff>0.05):
	    mstr ="Test: |IgndSP-IgndAvg|<50mA? : FAIL"	
	    ax.text(0.4, 0.07,mstr,transform=ax.transAxes, fontsize=10,verticalalignment='top', bbox=bad)
	else:
	    mstr ="Test: |IgndSP-IgndAvg|<50mA? : PASS"
	    ax.text(0.4, 0.07,mstr,transform=ax.transAxes, fontsize=10,verticalalignment='top', bbox=good)
	
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_IGND_Smooth.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	f,ax = plt.subplots(figsize=(8,4))
	ax.plot(SPR)
	ax.grid(True)
	ax.set_xlabel("10KHz Samples")
	ax.set_ylabel("Current (A)")
	ax.set_title("SPARE Smooth Test")
	plt.pause(0.1)
	f.savefig('Chan'+str(chan)+'_SPARE_Smooth.png')
	plt.close(f)
	f.canvas.flush_events()   # ensure all GUI events are handled
	plt.pause(0.1)

	mstr = "Smooth Test Results:"
	Pstyle = ParagraphStyle(
		'Custom',
		parent=styles['Normal'],
		fontName='Helvetica',
		fontSize=16,        # 👈 Set font size here
		leading=20,          # Optional: line spacing
		alignment=TA_CENTER   # 👈 Centers the paragraph horizontally
	)

	title = Paragraph(mstr,Pstyle)
	elements.append(PageBreak())  
	elements.append(title)
	im = Image('Chan'+str(chan)+'_DAC_Smooth.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_DCCT1_Smooth.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_DCCT1_Smooth.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))

	elements.append(PageBreak())  
	elements.append(title)
	im = Image('Chan'+str(chan)+'_ERROR_Smooth.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_REG_Smooth.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_VOLT_Smooth.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))

	elements.append(PageBreak())  
	elements.append(title)
	im = Image('Chan'+str(chan)+'_IGND_Smooth.png',7*inch,3*inch)
	elements.append(im)
	elements.append(Spacer(width=1,height=0.1*inch))
	im = Image('Chan'+str(chan)+'_SPARE_Smooth.png',7*inch,3*inch)
	elements.append(im)
	caput(DacSP,0) #Channel test complete.  Set DAC SP to 0 Amps

###############################################################################################
# End of Report...Building....
###############################################################################################
doc.build(elements)
